SortedMap
Roktober/learn_golang pull request #2
Opened 2021-05-27 23:05 UTC by Roktober

Сделать пакет SortedMap реализующий структуру данных map но с порядком.

Суть этого класса : map[string]int но с сохраненным порядком ключей.
Т.е. мы можем доставать значения из мапы по порядку как их туда записывали.

Использовать его в такой задаче:

Взять текст (txt) https://english-e-reader.net/book/gone-with-the-wind-margaret-mitchell
Обработать его и найти слова:
- N наиболее употребимых слов из более чем M букв
- не встречающиеся ни в начале ни в конце предложения.
- Вывести в порядке как они встречались в тексте.
- Пунктуацию всю игнорируем (убираем)
- N=10, M=3 для этого текста

Для простоты конец предложения определяем по "." или по концу строки \n. Другие знаки препинания игнорируем.
Начало предложения - начало строки или с большой буквы после ". ".

Подумать над композицией программы.
Тестировать и бенчмаркать будем на других текстах. Читать лучше из stdin.

2021-05-30 21:12 UTC, korjavin reviewed
Предлагаю сравнить этот map с standard map

2021-05-30 21:12 UTC, korjavin commented on sorted_map_task/main.go
> +			log.Fatal(err)
Что то как то поздно для fatal ;)

2021-05-31 05:49 UTC, Roktober commented on sorted_map_task/textprocessor/text_test.go
> +BenchmarkProcessText_small_text-12        343267              3326 ns/op            1554 B/op         31 allocs/op
Не понимаю, почему на строке есть аллокации, а не тексте нету

2021-05-31 15:58 UTC, Roktober commented on sorted_map_task/main.go
> +			log.Fatal(err)
> Что то как то поздно для fatal ;)

Не понял подвоха

2021-06-01 20:21 UTC, korjavin commented on sorted_map_task/main.go
> +			log.Fatal(err)
Обычно в defer уже fatal не нужен за очень редкими исключениями.

2021-06-01 20:31 UTC, korjavin commented on sorted_map_task/ordered/vanil/map.go
> +	_, keyPresent := m.internalMap[key]
почему то принято использовать имена типа exist, ok как второй возвращаемый аргумент

2021-06-01 20:31 UTC, korjavin commented on sorted_map_task/ordered/vanil/map.go
> +func (m *OrderedMap) expandOrderedSlice() {
А зачем это вообще?

2021-06-01 20:34 UTC, korjavin reviewed
Положите пожалуйста make файл например что бы можно было собирать задачи.

Просто go build ./sorted_map не проходит

2021-06-01 20:41 UTC, korjavin requested changes

2021-06-01 20:41 UTC, korjavin commented on sorted_map_task/main.go
> +	//Scarlett 146
Scralett точно есть в начале предложения.

2021-06-01 20:41 UTC, korjavin commented on sorted_map_task/ordered/map.go
> +type PairContainer interface {
А где используется этот интерфейс?

2021-06-01 20:41 UTC, korjavin commented on sorted_map_task/ordered/map.go
> +func (i *MapStringInt) KeyPresent(key string) bool {
Мне кажется эта функция не будет правильно работать.

Что если коллизия хеша. Она же может быть?

2021-06-01 20:41 UTC, korjavin commented on sorted_map_task/ordered/map.go
> +func (i *MapStringInt) KeyPresent(key string) bool {
Строки 
"ad" и "bc" какой имеют хеш в вашем случае?

2021-06-01 20:41 UTC, korjavin commented on sorted_map_task/ordered/map.go
> +	if float32(i.Size)/float32(i.Cap) <= 0.75 {
Давайте и 0.75 и 3/2 вынесем в конструктор и потом добавим в тесты разные значения.

2021-06-01 20:41 UTC, korjavin commented on sorted_map_task/reader/reader.go
> +func ScanLinesByDotNewLine(data []byte, atEOF bool) (advance int, token []byte, err error) {
А есть же SplitFunc в scaner , её бы не хватило?

2021-06-01 20:41 UTC, korjavin commented on sorted_map_task/reader/reader.go
> +func CreateBufferedScanner(reader io.Reader, bufferMaxLen int, splitFunc bufio.SplitFunc) *bufio.Scanner {
Я бы наверное эту функцию не стал делать, создал бы scanner прямо в main (вкусовщина)

2021-06-01 20:41 UTC, korjavin commented on sorted_map_task/textprocessor/text.go
> +	re, err := regexp.Compile(`[^\w' ]`)
ух! ох!

2021-06-07 05:38 UTC, korjavin approved these changes

2021-06-29 19:23 UTC, merged